const SUPABASE_URL = 'https://zmzlwvrtyklhfkyyzzcs.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inptemx3dnJ0eWtsaGZreXl6emNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODExNjgzNDUsImV4cCI6MjA5Njc0NDM0NX0.9mt0pkfRTXxUx2HTr5lG3OxHumhp74EeEdivzk_fi4g';
window.supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
window.supabase = window.supabaseClient;
